"""initial schema

Revision ID: 88059cf558d3
Revises: 
Create Date: 2026-09-14 09:11:04.420549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88059cf558d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_id'), 'audit_log_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entity_type'), 'audit_log_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_entry_id'), 'audit_log_entries', ['entry_id'], unique=True)
    op.create_index(op.f('ix_audit_log_entries_event_type'), 'audit_log_entries', ['event_type'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY_INDEX', 'RATE', 'FX', 'COMMODITY', 'CREDIT', 'CRYPTO', name='assetclass'), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('calendar', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_instruments_symbol')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('macro_data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('indicator_code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('GROWTH', 'INFLATION', 'MONETARY_POLICY', 'FINANCIAL_CONDITIONS', name='macrocategory'), nullable=False),
    sa.Column('frequency', sa.Enum('TICK', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='frequency'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('original_value', sa.Float(), nullable=True),
    sa.Column('revised_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'effective_date'),
    sa.UniqueConstraint('country', 'indicator_code', 'effective_date', 'revision_date', 'source', name='uq_macro_data_point_identity')
    )
    op.create_index('ix_macro_country_indicator_effective', 'macro_data_points', ['country', 'indicator_code', 'effective_date'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('market_data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frequency', sa.Enum('TICK', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='frequency'), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('original_value', sa.Float(), nullable=True),
    sa.Column('revised_value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp'),
    sa.UniqueConstraint('instrument_id', 'timestamp', 'frequency', 'source', name='uq_market_data_point_identity')
    )
    op.create_index('ix_market_data_instrument_timestamp', 'market_data_points', ['instrument_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_points_effective_date'), 'market_data_points', ['effective_date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'WATCHLIST', 'APPROVED', 'OPEN', 'REDUCE', 'CLOSED', 'INVALIDATED', name='tradestatus'), nullable=False),
    sa.Column('thesis', sa.String(length=4000), nullable=True),
    sa.Column('macro_score', sa.Float(), nullable=True),
    sa.Column('valuation_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('positioning_score', sa.Float(), nullable=True),
    sa.Column('catalyst_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('portfolio_risk_pct', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=64), nullable=True),
    sa.Column('pm_approved_by', sa.String(length=128), nullable=True),
    sa.Column('pm_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###

    # Convert the two PIT tables into TimescaleDB hypertables when the extension is
    # available (the timescale/timescaledb Docker image used in docker-compose.yml).
    # No-ops on plain PostgreSQL (e.g. local dev/test without Timescale installed) so
    # this migration works identically in both environments.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb') THEN
                CREATE EXTENSION IF NOT EXISTS timescaledb;
                PERFORM create_hypertable('market_data_points', 'timestamp',
                                           if_not_exists => TRUE, migrate_data => TRUE);
                PERFORM create_hypertable('macro_data_points', 'effective_date',
                                           if_not_exists => TRUE, migrate_data => TRUE);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_index(op.f('ix_market_data_points_effective_date'), table_name='market_data_points')
    op.drop_index('ix_market_data_instrument_timestamp', table_name='market_data_points')
    op.drop_table('market_data_points')
    op.drop_table('portfolios')
    op.drop_index('ix_macro_country_indicator_effective', table_name='macro_data_points')
    op.drop_table('macro_data_points')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_audit_log_entries_event_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entry_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_entity_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###

    # sa.Enum's CREATE TYPE is not reverted by drop_table, so it must be dropped
    # explicitly or a re-upgrade after downgrade fails with "type already exists".
    for enum_name in ("assetclass", "frequency", "macrocategory", "tradedirection", "tradestatus"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
