"""add regime_snapshots table

Revision ID: b94d42dde799
Revises: 88059cf558d3
Create Date: 2026-09-14 11:04:24.883682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94d42dde799'
down_revision: Union[str, None] = '88059cf558d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('growth_bucket', sa.Integer(), nullable=True),
    sa.Column('inflation_score', sa.Float(), nullable=True),
    sa.Column('inflation_bucket', sa.Integer(), nullable=True),
    sa.Column('monetary_policy_score', sa.Float(), nullable=True),
    sa.Column('monetary_policy_bucket', sa.Integer(), nullable=True),
    sa.Column('financial_conditions_score', sa.Float(), nullable=True),
    sa.Column('financial_conditions_bucket', sa.Integer(), nullable=True),
    sa.Column('regime_label', sa.Enum('GOLDILOCKS', 'REFLATION', 'STAGFLATION', 'DEFLATION', 'RECOVERY', 'LATE_CYCLE', 'RISK_OFF', 'LIQUIDITY_CRISIS', name='regimelabel'), nullable=False),
    sa.Column('regime_confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'as_of', 'model_version', name='uq_regime_snapshot_identity')
    )
    op.create_index(op.f('ix_regime_snapshots_as_of'), 'regime_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_regime_snapshots_country'), 'regime_snapshots', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regime_snapshots_country'), table_name='regime_snapshots')
    op.drop_index(op.f('ix_regime_snapshots_as_of'), table_name='regime_snapshots')
    op.drop_table('regime_snapshots')
    # ### end Alembic commands ###

    # sa.Enum's CREATE TYPE is not reverted by drop_table - see the same fix in the
    # initial_schema migration for why this is needed before a re-upgrade can succeed.
    op.execute("DROP TYPE IF EXISTS regimelabel")
